version: "3.7"

services:
  voltaml:
    image: voltaml:latest
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}

    volumes:
      - engine:/workspace/voltaML-fast-stable-diffusion/engine
      - /home/kubuntu/tmp/outputs:/workspace/voltaML-fast-stable-diffusion/outputs
      - cache:/root/.cache/huggingface
    ports:
      - "5003:5003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

volumes:
  engine: {}
  cache: {}
