version: "3.7"

services:
  voltaml:
    image: stax124/volta:experimental
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - FASTAPI_ANALYTICS_KEY=${FASTAPI_ANALYTICS_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - EXTRA_ARGS=${EXTRA_ARGS}
    volumes:
      - /home/kubuntu/Coding/voltaML/tmpdata:/app/data # XXX is the path to the folder where all the outputs will be saved
      - /home/kubuntu/Coding/voltaML/tmpcache:/root/.cache/huggingface # YYY is path to your home folder (you may need to change the YYY/.cache/huggingface to YYY\.cache\huggingface on Windows)
    ports:
      - "5003:5003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

volumes:
  cache: {}
