version: "3.7"

services:
  voltaml:
    image: stax124/volta_diffusion_webui:local
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /home/kubuntu/tmp/data:/workspace/voltaML-fast-stable-diffusion/data
      - /home/kubuntu/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "5003:5003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

volumes:
  cache: {}
